name: CI

on:
  pull_request:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: freckle/stack-cache-action@main
      - uses: freckle/stack-action@main
        with:
          hlint: false
          weeder: false

      - run: stack exec blog build

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - id: prep
        run: |
          get_output() {
            aws cloudformation describe-stacks \
              --stack-name sites-blog \
              --query 'Stacks[*].Outputs[?OutputKey==`'"$1"'`].OutputValue' \
              --output text
          }

          printf '::set-output name=bucket::%s\n' "$(get_output BucketName)"
          printf '::set-output name=distribution-id::%s\n' "$(get_output DistributionId)"

      - if: ${{ github.ref != 'refs/heads/main' }}
        run: |
          aws s3 sync --dryrun --acl public-read --delete _site \
            s3://${{ steps.prep.outputs.bucket }}

      - if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          aws s3 sync --acl public-read --delete _site \
            s3://${{ steps.prep.outputs.bucket }}
          aws cloudfront create-invalidation \
            --distribution-id ${{ steps.prep.outputs.distribution-id }} \
            --paths "/*"
