name: CI

on:
  pull_request:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: freckle/stack-cache-action@main
      - uses: freckle/stack-action@main
        with:
          hlint: false
          weeder: false

      - run: stack exec blog build

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - id: prep
        run: |
          aws cloudformation describe-stacks --stack-name sites-blog --output json |
            jq --raw-output '.Stacks[0].Outputs[] | "::set-output name=" + .OutputKey + "::" + .OutputValue'

      - if: ${{ github.ref == 'refs/heads/main' }}
        uses: restyled-io/aws-s3-sync-by-hash-action@main
        with:
          root: _site
          bucket: ${{ steps.prep.outputs.BucketName }}
          delete: true

      - if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ steps.prep.outputs.DistributionId }} \
            --paths "/*"
